name: gudang_ppli
description: Aplikasi Gudang PPLi Manyar Smelter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: any
  intl: any

flutter:
  uses-material-design: true
